- bke-runtime/gp-bke-runtime-minimal-application/README.md
- bke-runtime/gp-bke-runtime-minimal-application/templates/_helpers.tpl
- bke-runtime/gp-bke-runtime-minimal-application/templates/_helpers_pg.tpl
- bke-runtime/gp-bke-runtime-minimal-application/templates/deployment.yaml
- bke-runtime/gp-bke-runtime-minimal-application/templates/route.yml
- bke-runtime/gp-bke-runtime-minimal-application/templates/service.yaml
- bke-runtime/gp-bke-runtime-minimal-application/values.yaml
Es geht um gp-bke-runtime-minimal-application.
Das vorhandene `_helpers.tpl` war relativ komplex, mit viel Konfigurationsmöglichkeiten die teilweise nicht funktioniert haben. Ich habe es daher mal fast auf minimal zusammengestrichen und die Namen vereinheitlicht/vereinfacht. Die Idee dahinter:
- Die Servicename und Route-Namen sollten keine internen technischen Bezüge haben (BKE-Name), da sie von außen oder anderen Komponenten ansprechbar sein sollen. Sollten rein fachlich motiviert sein.
- Die Helm-Charts haben eher einen technischen Bezug und sind eventuell nicht auf einen Namespace beschränkt(?)
- Daher: Namen sind per Default _Release.Name_ aber mit _nameOverride_ (gefällt mir nicht sonderlich) überschreibbar.
- Prefix `svc-` habe ich weggelassen (`i-count` für Variablenbenennung …
> GPX-212 bke naming

- infra/gp-cluster-config/values.yaml
MySQL deployed nicht mit <200Mi, daher am Play Cluster angepasst und hier nachgezogen.
> GPX-232 allow wider range for limits

- infra/gp-cluster-update-checker/values.yaml
Da der Kubernetes Schedule in UTC ist und nicht in unserer Zeit startet das Update im Winter um 6 bzw. Sommer um 7 Uhr. 
Auf Kundencluster kann es allerdings vorkommen, dass zu diesem Zeitpunkt schon mit dem Cluster gearbeitet wird und dieser aufgrund des Updates langsamer reagiert.
> start cluster update at 3 UTC instead of 5 UTC

- day-2-operations/gp-cluster-setup/values.yaml
- day-2-operations/gp-cluster-setup/values/values-play.yaml
- day-2-operations/gp-cluster-setup/values/values-prod.yaml
- day-2-operations/gp-cluster-setup/values/values-steppe.yaml
- infra/gp-cluster-logging-eventrouter/.helmignore
- infra/gp-cluster-logging-eventrouter/Chart.yaml
- infra/gp-cluster-logging-eventrouter/templates/clusterrole.yaml
- infra/gp-cluster-logging-eventrouter/templates/clusterrolebinding.yaml
- infra/gp-cluster-logging-eventrouter/templates/configmap.yaml
- infra/gp-cluster-logging-eventrouter/templates/deployment.yaml
- infra/gp-cluster-logging-eventrouter/templates/serviceaccount.yaml
- infra/gp-cluster-logging-eventrouter/values.yaml
Im openshift-logging namespace wird ein pod gestartet der auf stdout die events aller namespaces loggt.
vor dem merge muss die manuelle installation über helm entfernt werden.
> GPX-276 - Events persistieren

- infra/gp-storage-cephcluster/Chart.yaml
- infra/gp-storage-cephcluster/templates/06-volumesnapshotclass.yaml
- infra/gp-storage-cephcluster/values.yaml
Retention Policy Delete, weil: Snapshots auf ein externes Storage-Backup exportiert werden und im Cluster sowieso gelöscht werden sollen nach dem Export.
> GPX-319 VolumesnapshotClass bei Ceph installation hinzufugen

- day-2-operations/gp-cluster-setup/values.yaml
- day-2-operations/gp-cluster-setup/values/values-steppe.yaml
- infra/gp-kasten-instance/templates/03-serviceaccount.yaml
- infra/gp-kasten-operator/values.yaml
helm lookup doesn't work in combination with ArgoCD.
Workaround is to ignoreDifference in this section in spec and add the required by hand.
Dokumentation: https://gepardec.atlassian.net/wiki/spaces/G/pages/2429550593/Kasten
Doku IgnoreDifferences: https://tost.dev/blog/ignore_differences_in_argocd/
> GPX-321 Kasten Refactoring Authentication

- bke-development/gp-cicd-sonarqube/Chart.yaml
- bke-development/gp-cicd-sonarqube/values.yaml
Maven Sonar-Plugin verwendet die Pfade /batch und /api. Da wir keine Möglichkeit haben über den Source Code eine OpenShift Authentication durchzuführen, müssen die beiden Pfade im Proxy ausgenommen werden. 
Die Authentifizierung, ob ein Projekt analysiert werden kann oder nicht erfolgt über den sonar.login token.
> fix Sonarqube Aufruf in Maven-Build

- infra/gp-cluster-monitoring-config/Chart.yaml
- infra/gp-cluster-monitoring-config/templates/prometheusrule.yaml
Im container gibt es anscheinend 3 engines und die teilen sich die max concurrent von 20.
> GPX-395 - alerting wenn thanos queries stecken

- bke-development/gp-cicd-eventbus/Chart.yaml
- bke-development/gp-cicd-eventbus/templates/monitoring.yaml
Gelegentlich kommt es vor, dass githooks argo workflows nicht triggern.
Da kann es sein, dass der eventbus cluster einen schiefstand hat und ein pod gelöscht werden muss.
Damit wir das mitbekommen müssen zuerst die metriken gesammelt werden.
Eine Prometheus rule soll dann feuern wenn in den letzten 4 stunden ein error dazugekommen.
> GPX-177 - eventbus error monitoren

- infra/gp-rook-ceph-operator/Chart.yaml
- infra/gp-rook-ceph-operator/templates/namespace.yaml
Wenn man in der console auf alerts drückt ist default, dass keine user alerts angezeigt werden.
> GPX-177 - rook-ceph metriken sollen im platform prometheus landen

- bke-development/gp-cicd-tools/values.yaml
OpenShift GitOps ist mittlerweile in der Version 1.6. verfügbar. Diese kommt mit: 
- Helm 3.8.1
- Kustomize 4.4.1
- ArgoCD 2.4.5
und liefert zum einen: Notifications Controller (sollten wir uns ansehen) und die Möglichkeit Custom ArgoCD Plugins zu verwenden. Ein eigenes ArgoCD Image sollten wir dementsprechend nicht mehr benötigen. 
Zur Verwendung von eigenen Plugins und der Erweiterung von ArgoCD um diese:
https://argo-cd.readthedocs.io/en/stable/user-guide/config-management-plugins/
https://argo-cd.readthedocs.io/en/stable/operator-manual/custom_tools/
Build-Your-Own-Image wird zwar auch von ArgoCD auf deren Dokumentation beschrieben. Für neuere Version wird jedoch der Weg über init-Container und VolumeMounts präferiert. 
Solange wir keinen Bedarf an einem Custom-Image haben, sollten …
> use default in Image for ArgoCD Instance

- bke-development/gp-cicd-tools/Chart.yaml
- bke-development/gp-cicd-tools/templates/01-argocd-instance.yaml
- bke-development/gp-cicd-tools/values.yaml
- infra/gp-cluster-config/Chart.yaml
- infra/gp-cluster-config/templates/10-argocd-rbac-patch.yaml
- infra/gp-cluster-config/values.yaml
Initiale Berechtigungen für Gepardec und Gepaplexx gesetzt.
openshift-gitops ArgoCD: nur Gepaplexx hat admin Rechte, alle anderen User können sich einloggen, sehen aber nichts.
gepaplexx-cicd-tools ArgoCD: Gepaplexx ist admin, Gepardec darf Applications, Repositories und Projekte ändern.
> GPX-415: Autorisierung ArgoCD

- bke-development/gp-cicd-tools/.helmignore
- bke-development/gp-cicd-tools/Chart.yaml
- bke-development/gp-cicd-tools/rbac_templates/rbac.yaml
- bke-development/gp-cicd-tools/templates/02-rbac.yaml
- bke-development/gp-cicd-tools/templates/workflows-sso-config.yaml
- bke-development/gp-cicd-tools/values.yaml
Änderungen bei ServiceAccounts und deren Secrets für API-Token. Fix Permissions:
* Read-Only User darf logs sehen (wenn konfiguriert)
* Permissions auf Namespaces sollten durch Änderungen nun auch funktionieren. Template für RBAC in Namespaces hinzugefügt.
> GPX-296 [CICD] Permissions & Security Argo Workflows/CD

- infra/gp-grafana-instance/Chart.yaml
- infra/gp-grafana-instance/templates/01-grafana-crd.yaml
- infra/gp-grafana-instance/templates/02-system-datasources.yaml
Verwendung des Loki HTTP Gateways anstatt des querier-frontends direkt. Das http-gateway benötigt einen gültigen OpenShift Bearer Token, damit es Daten zurückliefert. Damit haben wir für Loki jetzt denselben Stand wie bei Prometheus und müssen nur noch den richtigen Token in Grafana haben und weiterleiten.
> Loki Permissions base

- infra/gp-cluster-logging-instance/Chart.yaml
- infra/gp-cluster-logging-instance/templates/lokistack.yaml
- infra/gp-cluster-logging-instance/values.yaml
Anpassungen Lokistack für: 
- Ruler grundsätzlich aktiviert. 
-  Opt-Out für Rule-Discovery hinzugefügt.
> Anpassungen Lokistack - Ruler und Logretention

- infra/gp-grafana-instance/Chart.yaml
- infra/gp-grafana-instance/templates/01-grafana-crd.yaml
- infra/gp-grafana-instance/templates/02-system-datasources.yaml
- infra/gp-grafana-instance/templates/05-rbac.yaml
- infra/gp-grafana-instance/values.yaml
wir verwenden einen cluster-admin bearer token damit wir grafana ohne einschränkungen verwenden können. die datasource sind somit gesetzt und werden nicht mehr überschrieben.
> GPX-468 - aufräumen von grafana konfiguration

- infra/gp-cluster-config/Chart.yaml
- infra/gp-cluster-config/templates/11-kubeletconfig.yaml
Die Nodes werden alle bei Changes in dieser Config gedraint, allerdings tut es das hier hoffentlich nicht, da nur kommentare
> GPX-472: Warnhinweis als Kommentar

- infra/gp-cluster-monitoring-config/Chart.yaml
- infra/gp-cluster-monitoring-config/templates/00-cluster-monitoring-config.yaml
- raise remote_timeout from 30 to 60 seconds so less deadline exceeded happens
- send more samples per send from 500 to 8000
- lower max shard from 200 to 30 which makes it much more stable
- do not send selected metrics with very high cardinality
> Tune prometheus remote write

- infra/gp-cluster-monitoring-config/Chart.yaml
- infra/gp-cluster-monitoring-config/templates/08-alertmanager-config-external-secret.yaml
A pre-defined label is important because per default eso will apply its own labels which uses “instance” which therefore ArgoCD uses to determine if it should manage a resource. In this case, ArgoCD pruned the generated secret. For not already existing secrets, please consider using an owner reference.
> GPX-565: Added label to generated external secret alert-manager-main

- bke-development/gp-cicd-tools/templates/prometheusrules.yaml
Alert aufgrund zero alert policy gelöscht.
Ein Alert "argo-workflows-controller_memory_limit" existiert bereits.
> Deleted Alert "argo-workflows-controller_memory_saturation"

- bke-development/gp-cicd-tools/values.yaml
- infra/gp-cluster-update-checker/Chart.yaml
Unser Postgresql hat ein gesamtes Connection Limit auf 100 (default), per default hat die Argo Workflow denselben Wert für Limits auf seine idle connection.
Daher limit runterschalten, da Postgresql unabhängig der idle Connections von Workflows noch andere Connections verwaltet und daher zu viele Connections erhält.
> Updated idle connection limit to 50

- infra/gp-pipelines/.helmignore
- infra/gp-pipelines/Chart.yaml
- infra/gp-pipelines/templates/_helpers.tpl
- infra/gp-pipelines/templates/operator.yaml
Wie gestern besprochen: 
Ich habe den OpenShift Pipelines Operator, den wir gestern über die Web Console installiert haben gepackaged. Man kann ihn nun mit `helm install <Name> .` unter einen Namen installieren.
> Added Operator Subscription

- bke-development/gp-cicd-tools/Chart.yaml
- bke-development/gp-cicd-tools/templates/argocd-instance.yaml
fix argocd login issue über "Login via OpenShift"
siehe: https://issues.redhat.com/browse/GITOPS-2761
> Hotfix: Login über "Login via OpenShift" schlägt fehl mit openshift-gitops >= 1.8.0

- infra/gp-hashicorp-vault/helpers/vault-setup.sh
the cluster-config-reader still hat the policy for the backup create attached
> change the policy for the cluster-config-reader

- infra/gp-grafana-instance/Chart.yaml
- infra/gp-grafana-instance/templates/grafana-crd.yaml
- infra/gp-grafana-instance/values.yaml
+ Bump Grafana version from v9 to v10
+ added offline access scope for refresh tokens
+ added feature toggles including refresh token, correlations, editing data grids, nested folder, public Dashboards and auto migration of old panels
> bump: Grafana v9 -> v10

- infra/gp-keycloak-instance/Chart.yaml
- infra/gp-keycloak-instance/templates/db-backup-cron.yaml
- infra/gp-keycloak-instance/templates/db-backup-pvc.yaml
- infra/gp-keycloak-instance/values.yaml
.) moved backup configuration to top-level configuration instead of using postgres-subchart configuration for two types of backup
> fixes double postgresql backup

- infra/gp-hashicorp-vault/Chart.yaml
- infra/gp-hashicorp-vault/templates/BackupTestJob.yaml
vault cannot autounseal if it never has been initialized. Therefore vault server command needs to run in background in order for "vault operator init" to unseal and initialize empty vault before restoring the created backup.
> Bug(GPX-722): Vault Backuptester Stuck. 

- infra/gp-multena/Chart.yaml
- infra/gp-multena/templates/deployment.yaml
- infra/gp-multena/templates/rbac-collector/deployment.yaml
- infra/gp-multena/values.yaml
We are running Multena in a plain k8s environment, thus we need a way to disable volume mounts specific to Openshift envs. Additionally, I have added the option to set PodSecurityContext on proxy and collector pods. And finally, I have added support for defining topologySpreadConstraints for the proxy pods.
> Support vanilla k8s, PodSecurityContext and topologySpreadConstraints
