gepaplexx/gp-helm-chart-development

bke-runtime/gp-bke-runtime-database-mysql/.helmignore, bke-runtime/gp-bke-runtime-database-mysql/Chart.yaml, bke-runtime/gp-bke-runtime-database-mysql/templates/_helpers.tpl, bke-runtime/gp-bke-runtime-database-mysql/templates/secrets-connect.yaml, bke-runtime/gp-bke-runtime-database-mysql/values.yaml, bke-runtime/gp-bke-runtime-minimal-application/Chart.yaml, bke-runtime/gp-bke-runtime-minimal-application/templates/deployment.yaml, bke-runtime/gp-bke-runtime-minimal-application/values.yaml
BKE für MySQL.
Siehe [database-mysql/values.yaml](https://github.com/gepaplexx/bke-runtime-showcase/blob/main/database-mysql/values.yaml) für Beispiel.
=> GPX-232 MySQL Database BKE

bke-runtime/gp-bke-runtime-database-mysql/README.md, bke-runtime/gp-bke-runtime-minimal-application/templates/deployment.yaml
=> GPX-232 refactor range function

day-2-operations/gp-cluster-setup/values/values-play.yaml, day-2-operations/gp-cluster-setup/values/values-steppe.yaml, infra/gp-cluster-logging-instance/Chart.yaml, infra/gp-cluster-logging-instance/templates/07_clo-instance.yaml, infra/gp-cluster-logging-instance/values.yaml
Damit wir nicht in Memory Probleme laufen sollten wir Request und Limit gleich setzen.
Es wird außerdem empfohlen blockstorage zu verwenden.
Diese Storage Class ist auch erweiterbar.
Wir jetzt bei einem Merge Nach develop Argo aktiv? Falls ja müsste man es vorher in steppe entfernen.
In Play habe ich es nur manuell installiert.
=> Empfohlene Defaults setzen

bke-development/gp-cicd-sonarqube/.helmignore, bke-development/gp-cicd-sonarqube/Chart.yaml, bke-development/gp-cicd-sonarqube/templates/sonarqube-scc.yaml, bke-development/gp-cicd-sonarqube/values.yaml
Helm Chart für Installation von Sonarqube. Notwendige Anpassungen und Konfigurationen für OpenShift. 
@hwirnsberger beim JMX Exporter/Prometheus hat's noch was. Da brauch ich glaub ich deine Hilfe :)
=> GPX-317 added helm chart and configuration for SonarQube installation

infra/gp-cluster-monitoring-config/values.yaml
Also have a look at https://app.slack.com/client/T01FM3ACDKN/C03BPCP2VLH/thread/C03BPCP2VLH-1651904048.655359
=> GPX-299 - Increase storage

bke-development/gp-cicd-nexus/.helmignore, bke-development/gp-cicd-nexus/Chart.yaml, bke-development/gp-cicd-nexus/templates/01-rbac.yaml, bke-development/gp-cicd-nexus/templates/_helpers.tpl, bke-development/gp-cicd-nexus/values.yaml
Installation für zentralen Nexus Cache hinzugefügt!
=> GPX-318 Nexus Cache

infra/gp-cluster-config/templates/04-project-template.yaml
restrict storage class that should only be used in kasten namespace
https://access.redhat.com/solutions/3440181
=> GPX-321 Kasten NFS-StorageClass Restriction

bke-development/gp-cicd-apache/.helmignore, bke-development/gp-cicd-apache/Chart.yaml, bke-development/gp-cicd-apache/templates/_helpers.tpl, bke-development/gp-cicd-apache/templates/persistentvolumeclaim.yaml, bke-development/gp-cicd-apache/values.yaml
Helm Chart für Deployment eines Apache Webservers zum bereitstellen der jUnit Testergebnisse
=> GPX-339 Publishing von Test-Ergebnissen

infra/gp-cluster-config/templates/13-check-mk-rbac.yaml
=> GPX-340 CheckMK - Automatisiertes ClusterResource Monitoring

infra/gp-cluster-update-checker/templates/01-create-secret.yaml, infra/gp-cluster-update-checker/templates/01-sealed-secret.yaml
ClusterUpdater-Secret auf SealedSecret umgestellt
=> GPX-335 Cluster-Setup Aufteilung

bke-runtime/gp-bke-runtime-minimal-application/templates/deployment.yaml, bke-runtime/gp-bke-runtime-minimal-application/templates/hpa.yaml, bke-runtime/gp-bke-runtime-minimal-application/values.yaml
=> HorizontalPodAutoscaler zu bke-application hinzugefügt.

infra/gp-storage-cephcluster/Chart.yaml, infra/gp-storage-cephcluster/templates/mgr-service-monitor.yaml
ServiceMonitor zu helm Chart hinzugefügt
=> GPX-222 Rook-Ceph - Monitoring Enablen

bke-runtime/gp-bke-runtime-minimal-application/Chart.yaml, bke-runtime/gp-bke-runtime-minimal-application/templates/deployment.yaml
=> ReadinessProbe sollte nicht durch livenessProbe Value gesteuert werden

infra/gp-awx-monitoring/Chart.yaml, infra/gp-awx-monitoring/templates/prometheusrules.yaml
zusätzliche Alerts für unübliches CPU und Memory verhalten hinzugefügt
=> GPX-388 [Obversability] Monitoring von AWX

bke-development/gp-cicd-sonarqube/Chart.yaml, bke-development/gp-cicd-sonarqube/templates/rbac.yaml, infra/gp-cluster-config/Chart.yaml, infra/gp-cluster-config/templates/auth-rbac.yaml, infra/gp-grafana-instance/Chart.yaml, infra/gp-grafana-instance/templates/05-rbac.yaml
=> Clusterrole für authentication und authorization proxy zentralisiert

bke-development/gp-cicd-sonarqube/Chart.yaml, bke-development/gp-cicd-sonarqube/templates/oauth_patches.yaml, bke-development/gp-cicd-sonarqube/templates/rbac.yaml, bke-development/gp-cicd-sonarqube/templates/route.yaml, bke-development/gp-cicd-sonarqube/values.yaml
Helm-Chart angepasst, damit es mehr als einmal auf einem Cluster ausgerollt werden kann.
Zusätzliche Route hinzugefügt für Admin Login und Authorisierung
=> GPX-414 Autorisierung SonarQube

infra/gp-hub-monitoring/Chart.yaml, infra/gp-hub-monitoring/values.yaml
=> GPX-434 Authentifizierung Hub Grafana

infra/gp-cluster-config/Chart.yaml, infra/gp-cluster-config/templates/14-prometheus-rules.yaml
Alerting Rule für OCP Nodes hinzugefügt.
=> GPX-401: Service Monitoring: Nodes

bke-development/gp-cicd-tools/Chart.yaml, bke-development/gp-cicd-tools/values.yaml
Updated chart to version 0.20.1 (Argo Workflows 3.4.1)
=> GPX-477 Buildartefakte in der UI anzeigen (ab Argo Workflows 3.4)

infra/gp-cluster-config/Chart.yaml, infra/gp-cluster-config/templates/14-prometheus-rules.yaml
Hab die Grenzwerte für den Api- und den Kubeapiserver auf Basis der letzten 2 Wochen angepasst.
=> Prometheusregeln für Api- und Kubeapiserver angepasst

infra/gp-ocp-internal-registry/templates/01-pvc.yaml
added label to disable KubePersistentVolumeInodesFillingUp alert
=> bug/GPX-502 added label to disable KubePersistentVolumeInodesFillingUp alert

infra/gp-ocp-internal-registry/Chart.yaml
=> GPX-502: Bump version 1.1.2

infra/gp-cluster-logging-operator/Chart.yaml, infra/gp-cluster-logging-operator/templates/05_loki-sub.yaml, infra/gp-cluster-logging-operator/templates/06_clo-sub.yaml, infra/gp-cluster-logging-operator/values.yaml, infra/gp-grafana-operator/Chart.yaml, infra/gp-grafana-operator/templates/02-subscription.yaml, infra/gp-grafana-operator/values.yaml, infra/gp-kasten-operator/Chart.yaml, infra/gp-kasten-operator/templates/01-subscription.yaml, infra/gp-kasten-operator/values.yaml, infra/gp-keycloak-operator/Chart.yaml, infra/gp-keycloak-operator/templates/subscription.yaml, infra/gp-keycloak-operator/values.yaml, infra/gp-openshift-gitops/Chart.yaml, infra/gp-openshift-gitops/templates/subscription.yaml, infra/gp-openshift-gitops/values.yaml, infra/gp-patch-operator/Chart.yaml, infra/gp-patch-operator/templates/subscription.yaml, infra/gp-patch-operator/values.yaml
channel und installPlanApproval sind jetzt konfigurierbar
=> GPX-430: Subscription - UpdatePolicy konfigurierbar machen

infra/gp-hashicorp-vault/Chart.yaml, infra/gp-hashicorp-vault/helpers/vault-setup.sh
Enabled Audit-Logging for HashiCorp Vault
=> GPX-482 [LIWEST|Security] Logging-Anforderungen

infra/gp-awx-monitoring/Chart.yaml, infra/gp-awx-monitoring/templates/prometheusrules.yaml
Fehlende Klammer bei Prometheusregel ergänzt
=> GPX-447: Umbau auf Single Node Cluster

infra/gp-cluster-logging-instance/Chart.yaml, infra/gp-cluster-logging-instance/templates/clusterlogging.yaml
https://docs.openshift.com/container-platform/4.11/logging/config/cluster-logging-collector.html
=> vector log collector austauschen mit fluentd

infra/gp-cluster-monitoring-config/Chart.yaml, infra/gp-cluster-monitoring-config/templates/pvc-monitoring-prometheusrule.yaml, infra/gp-cluster-monitoring-config/values.yaml
- PVC wurde erhöht
- Alertschwelle wurde runtergesetzt
=> Feature/pvc_almost_full - Reaktion auf Prometheus PVC 90% Auslastung

bke-development/gp-cicd-tools/templates/prometheusrules.yaml
Alertingrule angelegt, die bei unsuccessfulen workflow runs feuert
=> GPX-294: Alertingrule für Workflowfehlschläge

infra/gp-kyverno/examplepolicies/networkpolicy-allow-from-ns.yaml, infra/gp-kyverno/examplepolicies/networkpolicy-default.yaml, infra/gp-kyverno/examplepolicies/quota-annotation.yaml, infra/gp-kyverno/examplepolicies/quota-requester-group.yaml, infra/gp-kyverno/examplepolicies/quota-simple.yaml
Beispiele für Kyverno hinzugefügt
=> GPX-539: Handling von Default-Ressourcen

infra/gp-external-secrets-configuration/templates/cicd-internal-cluster-store.yaml, infra/gp-hashicorp-vault/helpers/vault-setup.sh
Anpassungen an Berechtigungen in Vault-Setup
Erstellen neues Secret-Stores für Cluster Configuration Fix Syntax in Role
Use Correct Names
=> GPX-655 Secretmanagement ist implementiert

infra/gp-keycloak-configuration/Chart.yaml
pushing a chart and its dependency at the same time seems to not always work the way I want to...
=> feature/GPX-655 bump KC conf chart version

bke-development/gp-cicd-nexus/Chart.yaml, bke-development/gp-cicd-nexus/templates/service-monitor.yaml
To expose the metrics endpoint
=> GPX-538 Service Monitor for nexus

infra/gp-multena/Chart.yaml, infra/gp-multena/templates/configmaps.yaml, infra/gp-multena/templates/deployment.yaml, infra/gp-multena/templates/service.yaml, infra/gp-multena/templates/servicemonitor.yaml, infra/gp-multena/templates/system-datasources.yaml, infra/gp-multena/values.yaml
+ added service monitor
+ updated service
+ updated deployment
+ bumped version to v0.3.0
=> Feat(GPX-675): Metrics for Multena

infra/gp-multena/templates/deployment.yaml, infra/gp-multena/values.yaml
+ bump version, fixed secret path
multena: removed need for labels.yaml
=> fix(multena): labels.yaml panic

infra/gp-multena/Chart.yaml, infra/gp-multena/templates/deployment.yaml, infra/gp-multena/values.yaml
=> fix(multena): bump version

infra/gp-keycloak-instance/Chart.yaml, infra/gp-keycloak-instance/templates/db-backup-cron.yaml, infra/gp-keycloak-instance/templates/db-backup-pvc.yaml, infra/gp-keycloak-instance/values.yaml
S3-Backend hinzugefügt
Backup Job um sync der backups nach S3 Backend erweitert
=> GPX-710 [SSO] Keycloak Backups nach S3 syncen

infra/gp-grafana-operator/Chart.yaml, infra/gp-grafana-operator/values.yaml
Channel umgestellt und Chart Version angepasst.
=> GPX-674 Upgrade Grafana Operator to v5

bke-development/gp-cicd-tools/Chart.yaml, bke-development/gp-cicd-tools/values.yaml
+ added link in workflow scope to point to the workflow dashboard.
=> Feat(GPX-707): Link to Workflow Dashboard

infra/gp-grafana-instance/templates/monitoring.yaml
=> hotfix: alert for grafana

infra/gp-kyverno/Chart.yaml, infra/gp-kyverno/templates/alerts.yaml
=> Add an alert for high cpu usage of pods in the kyverno namespace
